## 本地图片上传路径
local:
  path: static
system:
  addr: 8000
  db-type: mysql
  oss-type: local
  use-multipoint: false
  iplimit-count: 15000
  iplimit-time: 3600
zap:
  level: info
  format: console
  prefix: '[overwrite]'
  director: log
  showLine: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
api_keys:
  apis:
    0: # 对应 OnlyRead
      X-VO-Api-Id: "your_only_read_api_id"
      X-VO-Api-Key: "your_only_read_api_key"
    1: # 对应 ReadWrite
      X-VO-Api-Id: "your_read_write_api_id"
      X-VO-Api-Key: "your_read_write_api_key"
